export const DATOS_FALLBACK = {
  resumen: {
    reputacion: 4.5,
    postulacionesActivas: 3,
    proyectosEnProgreso: 2,
    proyectosCompletados: 5,
    ofertasRecibidas: 1,
  },
  postulaciones: [
    {
      id_postulacion: 1,
      titulo: 'Desarrollador Frontend React',
      empresa: 'TechCorp',
      estado: 'EN_REVISION',
      fecha_postulacion: '2026-06-01T00:00:00.000Z',
    },
    {
      id_postulacion: 2,
      titulo: 'Full Stack Developer',
      empresa: 'InnovaLabs',
      estado: 'ACEPTADA',
      fecha_postulacion: '2026-05-15T00:00:00.000Z',
    },
    {
      id_postulacion: 3,
      titulo: 'UI/UX Designer',
      empresa: 'CreativeStudio',
      estado: 'RECHAZADA',
      fecha_postulacion: '2026-04-20T00:00:00.000Z',
    },
    {
      id_postulacion: 4,
      titulo: 'Backend Node.js Developer',
      empresa: 'DataFlow',
      estado: 'EN_REVISION',
      fecha_postulacion: '2026-06-10T00:00:00.000Z',
    },
    {
      id_postulacion: 5,
      titulo: 'Mobile Developer React Native',
      empresa: 'AppWorks',
      estado: 'PENDIENTE',
      fecha_postulacion: '2026-06-12T00:00:00.000Z',
    },
  ],
  proyectos: [
    {
      id_proyecto: 1,
      titulo: 'Rediseño Plataforma E-learning',
      empresa: 'EduTech',
      estado: 'EN_PROGRESO',
      fecha_inicio: '2026-05-01T00:00:00.000Z',
      fecha_fin_estimada: '2026-08-01T00:00:00.000Z',
      progreso: 65,
      entregables: [
        { id: 1, nombre: 'Wireframes', completado: true },
        { id: 2, nombre: 'Prototipo Figma', completado: true },
        { id: 3, nombre: 'Implementación Frontend', completado: false },
      ],
    },
    {
      id_proyecto: 2,
      titulo: 'App de Delivery',
      empresa: 'FoodGo',
      estado: 'EN_REVISION',
      fecha_inicio: '2026-03-15T00:00:00.000Z',
      fecha_fin_estimada: '2026-06-30T00:00:00.000Z',
      progreso: 90,
      entregables: [
        { id: 1, nombre: 'API REST', completado: true },
        { id: 2, nombre: 'App Mobile', completado: true },
        { id: 3, nombre: 'Documentación', completado: false },
      ],
    },
  ],
  historial: [
    {
      id: 1,
      titulo: 'Sistema de Ventas POS',
      empresa: 'ComercioCR',
      rol: 'Desarrollador Frontend',
      fecha_inicio: '2026-01-10T00:00:00.000Z',
      fecha_fin: '2026-04-20T00:00:00.000Z',
      estado: 'COMPLETADO',
      calificacion: 5,
      tipo: 'plataforma',
      repositorio: 'https://github.com/egresado/pos-system',
    },
    {
      id: 2,
      titulo: 'Landing Page Startup',
      empresa: 'GreenTech',
      rol: 'Diseñador UI/UX',
      fecha_inicio: '2025-11-01T00:00:00.000Z',
      fecha_fin: '2025-12-15T00:00:00.000Z',
      estado: 'COMPLETADO',
      calificacion: 4,
      tipo: 'plataforma',
    },
    {
      id: 3,
      titulo: 'API de Recomendaciones',
      empresa: 'Proyecto Personal',
      rol: 'Full Stack',
      fecha_inicio: '2025-08-01T00:00:00.000Z',
      fecha_fin: '2025-10-30T00:00:00.000Z',
      estado: 'COMPLETADO',
      calificacion: null,
      tipo: 'github',
      repositorio: 'https://github.com/egresado/recommend-api',
    },
  ],
  notificaciones: [
    {
      id: 1,
      tipo: 'postulacion',
      titulo: 'Postulación recibida',
      mensaje: 'Tu postulación para "Desarrollador Frontend React" ha sido recibida.',
      leido: false,
      creado_en: '2026-06-13T10:30:00.000Z',
    },
    {
      id: 2,
      tipo: 'proyecto',
      titulo: 'Nuevo entregable',
      mensaje: 'La empresa TechCorp ha solicitado una revisión del entregable.',
      leido: false,
      creado_en: '2026-06-12T14:00:00.000Z',
    },
    {
      id: 3,
      tipo: 'mensaje',
      titulo: 'Nuevo mensaje',
      mensaje: 'Tienes un nuevo mensaje de Maria Lopez (TechCorp).',
      leido: false,
      creado_en: '2026-06-11T09:15:00.000Z',
    },
    {
      id: 4,
      tipo: 'sistema',
      titulo: 'Recordatorio',
      mensaje: 'Tu proyecto "Rediseño Plataforma E-learning" tiene una entrega próxima.',
      leido: true,
      creado_en: '2026-06-10T08:00:00.000Z',
    },
  ],
  mensajes: [
    {
      id: 1,
      nombre_remitente: 'Maria Lopez',
      empresa: 'TechCorp',
      ultimo_mensaje: 'Hola, queremos saber tu disponibilidad para una entrevista técnica.',
      foto_perfil: null,
      leido: false,
      fecha_ultimo_mensaje: '2026-06-13T11:00:00.000Z',
    },
    {
      id: 2,
      nombre_remitente: 'Carlos Mora',
      empresa: 'InnovaLabs',
      ultimo_mensaje: 'Excelente trabajo en el proyecto. ¿Podemos agendar una reunión?',
      foto_perfil: null,
      leido: true,
      fecha_ultimo_mensaje: '2026-06-11T16:30:00.000Z',
    },
    {
      id: 3,
      nombre_remitente: 'Ana Jimenez',
      empresa: 'CreativeStudio',
      ultimo_mensaje: 'Gracias por tu interés. Te compartimos los detalles del proyecto.',
      foto_perfil: null,
      leido: true,
      fecha_ultimo_mensaje: '2026-06-09T10:00:00.000Z',
    },
  ],
  perfil: {
    nombre: 'Alex Rivera',
    correo: 'alex.rivera@fwd.com',
    telefono: '+506 8888-7777',
    ubicacion: 'San José, Costa Rica',
    titulo: 'Junior Frontend Developer',
    biografia: 'Desarrollador frontend apasionado por crear interfaces intuitivas y accesibles. Experiencia en React, Vue y diseño de UI/UX.',
    habilidades: ['React', 'JavaScript', 'CSS', 'Figma', 'Node.js', 'Git'],
    educacion: [
      { titulo: 'Técnico en Desarrollo Web', institucion: 'FWD', año: 2025 },
    ],
    experiencia: [
      { puesto: 'Frontend Developer Freelance', empresa: 'Varios Clientes', periodo: '2024-2025' },
    ],
    foto_perfil: null,
    linkedin: 'https://linkedin.com/in/alexrivera',
    portafolio: 'https://alexrivera.dev',
  },
};
