export const DATOS_FALLBACK = {
  resumen: {
    reputacion: 4.5,
    postulacionesActivas: 3,
    proyectosEnProgreso: 2,
    proyectosCompletados: 5,
    ofertasRecibidas: 1,
  },
  postulaciones: [
    {
      id_postulacion: 1,
      id_propuesta: 1,
      estado: 'EN_REVISION',
      fecha_postulacion: '2026-06-01T00:00:00.000Z',
      mensaje_presentacion: 'Me encantaría trabajar en este proyecto. Tengo experiencia en React y TypeScript.',
      propuesta: {
        id_propuesta: 1,
        titulo: 'Desarrollador Frontend React',
        descripcion: 'Buscamos un desarrollador frontend con experiencia en React y TypeScript para unirse a nuestro equipo.',
        tecnologias_requeridas: 'React, TypeScript, CSS, Node.js',
        presupuesto_max: 3000,
      },
    },
    {
      id_postulacion: 2,
      id_propuesta: 2,
      estado: 'ENVIADA',
      fecha_postulacion: '2026-05-15T00:00:00.000Z',
      mensaje_presentacion: null,
      propuesta: {
        id_propuesta: 2,
        titulo: 'Full Stack Developer',
        descripcion: 'Proyecto de plataforma educativa que requiere un desarrollador full stack.',
        tecnologias_requeridas: 'Node.js, React, PostgreSQL, Docker',
        presupuesto_max: 5000,
      },
    },
    {
      id_postulacion: 3,
      id_propuesta: 3,
      estado: 'RECHAZADA',
      fecha_postulacion: '2026-04-20T00:00:00.000Z',
      mensaje_presentacion: 'Soy diseñador UI/UX con 3 años de experiencia en Figma.',
      propuesta: {
        id_propuesta: 3,
        titulo: 'UI/UX Designer',
        descripcion: 'Necesitamos un diseñador para rediseñar la interfaz de nuestra aplicación.',
        tecnologias_requeridas: 'Figma, Adobe XD, CSS',
        presupuesto_max: 2500,
      },
    },
    {
      id_postulacion: 4,
      id_propuesta: 4,
      estado: 'PRESSELECCIONADA',
      fecha_postulacion: '2026-06-10T00:00:00.000Z',
      mensaje_presentacion: null,
      propuesta: {
        id_propuesta: 4,
        titulo: 'Backend Node.js Developer',
        descripcion: 'Desarrollo de API REST para sistema de análisis de datos.',
        tecnologias_requeridas: 'Node.js, Express, MongoDB, Redis',
        presupuesto_max: 4000,
      },
    },
    {
      id_postulacion: 5,
      id_propuesta: 5,
      estado: 'CONTRATADO',
      fecha_postulacion: '2026-06-12T00:00:00.000Z',
      mensaje_presentacion: 'Tengo experiencia desarrollando apps con React Native.',
      propuesta: {
        id_propuesta: 5,
        titulo: 'Mobile Developer React Native',
        descripcion: 'Crear una aplicación móvil multiplataforma con React Native.',
        tecnologias_requeridas: 'React Native, TypeScript, Firebase',
        presupuesto_max: 3500,
      },
    },
  ],
  proyectos: [
    {
      id_proyecto: 1,
      titulo: 'Rediseño Plataforma E-learning',
      empresa: 'EduTech',
      estado: 'EN_PROGRESO',
      fecha_inicio: '2026-05-01T00:00:00.000Z',
      fecha_fin_estimada: '2026-08-01T00:00:00.000Z',
      progreso: 65,
      entregables: [
        { id: 1, nombre: 'Wireframes', completado: true },
        { id: 2, nombre: 'Prototipo Figma', completado: true },
        { id: 3, nombre: 'Implementación Frontend', completado: false },
      ],
    },
    {
      id_proyecto: 2,
      titulo: 'App de Delivery',
      empresa: 'FoodGo',
      estado: 'EN_REVISION',
      fecha_inicio: '2026-03-15T00:00:00.000Z',
      fecha_fin_estimada: '2026-06-30T00:00:00.000Z',
      progreso: 90,
      entregables: [
        { id: 1, nombre: 'API REST', completado: true },
        { id: 2, nombre: 'App Mobile', completado: true },
        { id: 3, nombre: 'Documentación', completado: false },
      ],
    },
  ],
  historial: [
    {
      id_historial_estudiante: 1,
      id_perfil_estudiante: 1,
      titulo_proyecto: 'Sistema de Ventas POS',
      tipo: 'PLATAFORMA',
      descripcion: 'Desarrollo de un sistema punto de venta completo con inventario, facturación y reportes.',
      enlace: 'https://github.com/egresado/pos-system',
      tecnologias: 'React,Node.js,PostgreSQL',
      rol_desempenado: 'Desarrollador Frontend',
      fecha_inicio: '2026-01-10',
      fecha_fin: '2026-04-20',
    },
    {
      id_historial_estudiante: 2,
      id_perfil_estudiante: 1,
      titulo_proyecto: 'Landing Page Startup',
      tipo: 'PLATAFORMA',
      descripcion: 'Diseño y maquetación de landing page para startup de tecnología verde.',
      enlace: null,
      tecnologias: 'Figma,HTML,CSS',
      rol_desempenado: 'Diseñador UI/UX',
      fecha_inicio: '2025-11-01',
      fecha_fin: '2025-12-15',
    },
    {
      id_historial_estudiante: 3,
      id_perfil_estudiante: 1,
      titulo_proyecto: 'API de Recomendaciones',
      tipo: 'GITHUB',
      descripcion: 'API REST para sistema de recomendaciones usando machine learning.',
      enlace: 'https://github.com/egresado/recommend-api',
      tecnologias: 'Python,Flask,TensorFlow',
      rol_desempenado: 'Full Stack',
      fecha_inicio: '2025-08-01',
      fecha_fin: '2025-10-30',
    },
  ],
  notificaciones: [
    {
      id_notificacion: 1,
      id_usuario: 1,
      tipo: 'postulacion',
      mensaje: 'Tu postulación para "Desarrollador Frontend React" ha sido recibida.',
      leido: false,
      fecha: '2026-06-13T10:30:00.000Z',
    },
    {
      id_notificacion: 2,
      id_usuario: 1,
      tipo: 'proyecto',
      mensaje: 'La empresa TechCorp ha solicitado una revisión del entregable en "Rediseño Plataforma E-learning".',
      leido: false,
      fecha: '2026-06-12T14:00:00.000Z',
    },
    {
      id_notificacion: 3,
      id_usuario: 1,
      tipo: 'mensaje',
      mensaje: 'Tienes un nuevo mensaje de Maria Lopez (TechCorp).',
      leido: false,
      fecha: '2026-06-11T09:15:00.000Z',
    },
    {
      id_notificacion: 4,
      id_usuario: 1,
      tipo: 'sistema',
      mensaje: 'Tu proyecto "Rediseño Plataforma E-learning" tiene una entrega próxima.',
      leido: true,
      fecha: '2026-06-10T08:00:00.000Z',
    },
  ],
  mensajes: [
    {
      id: 1,
      nombre_remitente: 'Maria Lopez',
      empresa: 'TechCorp',
      ultimo_mensaje: 'Hola, queremos saber tu disponibilidad para una entrevista técnica.',
      foto_perfil: null,
      leido: false,
      fecha_ultimo_mensaje: '2026-06-13T11:00:00.000Z',
    },
    {
      id: 2,
      nombre_remitente: 'Carlos Mora',
      empresa: 'InnovaLabs',
      ultimo_mensaje: 'Excelente trabajo en el proyecto. ¿Podemos agendar una reunión?',
      foto_perfil: null,
      leido: true,
      fecha_ultimo_mensaje: '2026-06-11T16:30:00.000Z',
    },
    {
      id: 3,
      nombre_remitente: 'Ana Jimenez',
      empresa: 'CreativeStudio',
      ultimo_mensaje: 'Gracias por tu interés. Te compartimos los detalles del proyecto.',
      foto_perfil: null,
      leido: true,
      fecha_ultimo_mensaje: '2026-06-09T10:00:00.000Z',
    },
  ],
  perfil: {
    nombre: 'Alex Rivera',
    correo: 'alex.rivera@fwd.com',
    telefono: '+506 8888-7777',
    foto_perfil: null,
    titulo_fwd: 'Junior Frontend Developer',
    descripcion: 'Desarrollador frontend apasionado por crear interfaces intuitivas y accesibles. Experiencia en React, Vue y diseño de UI/UX.',
    sede_graduacion: 'San José',
    reputacion_total: 4.5,
    tecnologias: ['React', 'JavaScript', 'CSS', 'Figma', 'Node.js', 'Git'],
    portfolio: 'https://alexrivera.dev',
    linkedin: 'https://linkedin.com/in/alexrivera',
    educacion: [
      { titulo: 'Técnico en Desarrollo Web', institucion: 'FWD', año: 2025 },
    ],
    experiencia: [
      { puesto: 'Frontend Developer Freelance', empresa: 'Varios Clientes', periodo: '2024-2025' },
    ],
    resumen_profesional: '',
    certificaciones: '',
  },
};
